version: '3.8'

services:
  db:
    image: postgres:latest  # PostGIS-enabled PostgreSQL image
    container_name: tasklist-db  # Updated container name
    environment:
      POSTGRES_USER: tasklist_user  # Updated database user
      POSTGRES_PASSWORD: tasklist_pass  # Updated database password
      POSTGRES_DB: tasklist_db  # Updated database name
    ports:
      - "5432:5432"
    networks:
      - tasklist-network
    volumes:
      - tasklist_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: tasklist-web  # Updated container name
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: tasklist-db  # Updated to match db service name
      DB_NAME: tasklist_db  # Updated database name
      DB_USER: tasklist_user  # Updated database user
      DB_PASSWORD: tasklist_pass  # Updated database password
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - tasklist-network

  pgadmin:
    image: dpage/pgadmin4:latest  # Latest pgAdmin image
    container_name: tasklist-pgadmin  # Updated container name
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Default email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin  # Default password for pgAdmin
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    depends_on:
      - db
    networks:
      - tasklist-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  tasklist-network:

volumes:
  tasklist_data:
  pgadmin_data:
